### ISSUE TITLE
array of records?

### ISSUE THREAD

**Issue by anujbiyani** [salsify/avro-builder#34]
I'm trying to write a record where one of the fields is an array where each item is a record. I can do this if I don't inline the inner-most record, e.g.
```ruby
record :record_in_array do
  required :name, :string
end

record :top_level do
  required :array_of_records, :array, items: :record_in_array
end
```

Is it possible to inline the `record_in_array` record? The following errors:
```ruby
record :top_level do
  required :array_of_records, :array, items: :record do
    required :name, :string
  end
end

#> NoMethodError: undefined method `required' for #<Avro::Builder::Field:0x007fdd3437d278>
```

**Comment by tjwp** [comment]
No, it's not currently possibly to inline the definition of a record as the item for an array (or the value for a map).

Is there a use case where it is problematic to separately define the record for the array items?

**Comment by anujbiyani** [comment]
We have schemas where we have 10-20 arrays that each consist of records that have maybe one or two fields; each record is therefore quite small, and there are a lot of them, so it'd be nice to have them inlined. Other than that it's not a significant issue. Would you be open to a PR that added this functionality in?

(We can't simplify the schema because it's designed around a message we receive from a third party system.)

**Comment by tjwp** [comment]
Definitely open to a PR if you want to add it.

A couple of things to keep in mind: 
- the type for a field can be either a symbol for the type name or a Type object. So `required :array_of_ints, :array, items: :int` and `required :array_of_ints, array(:int)` are equivalent.
- items can be specified as an option or as a method in the block when the the field type is `:array`
- the value for items can also be either a symbol for a type name or a Type object

I mention these because instead of supporting the syntax in your example, it may be easier to expose a record method that returns a type:

```ruby
record :top_level do
  required :array_of_records, :array, items: (record { required :name, :string })
end

# OR

record :top_level do
  required :array_of_records, :array do
    items (record { required :name, :string })
  end
end

# OR

record :top_level do
  required :array_of_records, array(record { required :name, :string })
end
```

**Comment by anujbiyani** [comment]
Ah okay, thanks for the tips! Not sure if I'll have time or not but hopefully I can find some =)

Closing this issue as it's been resolved.
